services:
  app:
    build: .
    container_name: smart-api-hub
    restart: unless-stopped
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:18.4
    container_name: smart-api-hub-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: manhnd111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
