services:
  app:
    build: .
    container_name: manhnd111-smart-api-hub
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    env_file:
      - .env
  postgres:
    image: postgres:18.4
    container_name: manhnd111-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
